[package]
name = "smolvlm_demo"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "smolvlm_demo"
path = "src/main.rs"

[dependencies]
kornia-models = { path = "../../crates/kornia-models" }